name: build
on: [push, pull_request]

jobs:
  screego:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: actions/checkout@v4
      - run: go mod download
      - run: (cd ui && yarn)
      - run: (cd ui && yarn build)
      - run: (cd ui && yarn testformat)
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.60.3
      - run: go build ./...
      - run: go test -race ./...
      - if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username "${{ github.actor }}" --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@v5
        with:
          version: 1.22.1
          args: release --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
